spring.datasource.url=jdbc:mysql://localhost:3306/hospitall
spring.datasource.username=root
spring.datasource.password=pavani

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
